# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161224_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('household', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Household')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='type',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Household', 'Household')], default='Personal', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
        ),
    ]
