# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 09:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161224_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('remainder', models.DecimalField(decimal_places=2, max_digits=8)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Household')),
            ],
        ),
        migrations.CreateModel(
            name='MasterBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='masterBudget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MasterBudget'),
        ),
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='record',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Budget'),
        ),
    ]
