# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_record_masterbudget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='masterBudget',
        ),
    ]
