# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_budget_masterbudget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='masterbudget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.MasterBudget'),
            preserve_default=False,
        ),
    ]
