# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 16:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_budget_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='household',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='name',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='user',
        ),
        migrations.AddField(
            model_name='budget',
            name='time_range',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterbudget',
            name='expense_type',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Household', 'Household')], default='Personal', max_length=50),
        ),
        migrations.AddField(
            model_name='masterbudget',
            name='period',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Weekly', 'Weekly'), ('Daily', 'Daily')], default='Monthly', max_length=50),
        ),
    ]
