# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20161225_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='time_range',
        ),
        migrations.AddField(
            model_name='budget',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
