# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-03 09:20
from __future__ import unicode_literals

from django.db import migrations


def move_categories(apps, schema_editor):
    Record = apps.get_model('api', 'Record')
    for r in Record.objects.all():
        if r.category:
            r.categories.add(r.category)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20170603_0919'),
    ]

    operations = [
        migrations.RunPython(move_categories)
    ]
