# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-03 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20170603_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='category',
        ),
    ]
